# Need to space each word so It doesn't get confusing :D
SORBET_SHARK_COOKIE_PHRASES = {
text.replace("a", "OoO "),
text.replace("b", "ooO "),
text.replace("c", "Ooo "),
text.replace("d", "O-o "),
text.replace("f", "OOo "),
text.replace("g", "oOo "),
text.replace("h", "O-O "),
text.replace("i", "o-o-o "),
text.replace("j", "O--O "),
text.replace("k", "oOuú "),
text.replace("l", "OoŒ "),
text.replace("m", "oÖ "),
text.replace("n", "OuUo "),
text.replace("o", "uuooOo "),
text.replace("p", "UuoOo "),
text.replace("q", "UuoOo "),
text.replace("r", "OuUuO "),
text.replace("s", "oOuuU "),
text.replace("t", "UuOo "),
text.replace("u", "UuOo "),
text.replace("v", "oouuuo "),
text.replace("w", "OuOo "),
text.replace("x", "OooOuu "),
text.replace("y", "uuooouu "),
text.replace("z", "ouuuouuu ")
}